//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.HTTP {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentType", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary")]
    public enum StudentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Regular = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Open = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HTTP.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudent", ReplyAction="http://tempuri.org/IStudentService/GetStudentResponse")]
        WCFClient.HTTP.StudentResponse GetStudent(WCFClient.HTTP.StudentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudent", ReplyAction="http://tempuri.org/IStudentService/GetStudentResponse")]
        System.Threading.Tasks.Task<WCFClient.HTTP.StudentResponse> GetStudentAsync(WCFClient.HTTP.StudentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StudentRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StudentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string StudentKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int StudentId;
        
        public StudentRequest() {
        }
        
        public StudentRequest(string StudentKey, int StudentId) {
            this.StudentKey = StudentKey;
            this.StudentId = StudentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Gender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string City;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public WCFClient.HTTP.StudentType Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int RegularFees;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int CourseHours;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int HourlyRate;
        
        public StudentResponse() {
        }
        
        public StudentResponse(int Id, string Name, string Gender, string City, WCFClient.HTTP.StudentType Type, int RegularFees, int CourseHours, int HourlyRate) {
            this.Id = Id;
            this.Name = Name;
            this.Gender = Gender;
            this.City = City;
            this.Type = Type;
            this.RegularFees = RegularFees;
            this.CourseHours = CourseHours;
            this.HourlyRate = HourlyRate;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : WCFClient.HTTP.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<WCFClient.HTTP.IStudentService>, WCFClient.HTTP.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFClient.HTTP.StudentResponse WCFClient.HTTP.IStudentService.GetStudent(WCFClient.HTTP.StudentRequest request) {
            return base.Channel.GetStudent(request);
        }
        
        public int GetStudent(string StudentKey, int StudentId, out string Name, out string Gender, out string City, out WCFClient.HTTP.StudentType Type, out int RegularFees, out int CourseHours, out int HourlyRate) {
            WCFClient.HTTP.StudentRequest inValue = new WCFClient.HTTP.StudentRequest();
            inValue.StudentKey = StudentKey;
            inValue.StudentId = StudentId;
            WCFClient.HTTP.StudentResponse retVal = ((WCFClient.HTTP.IStudentService)(this)).GetStudent(inValue);
            Name = retVal.Name;
            Gender = retVal.Gender;
            City = retVal.City;
            Type = retVal.Type;
            RegularFees = retVal.RegularFees;
            CourseHours = retVal.CourseHours;
            HourlyRate = retVal.HourlyRate;
            return retVal.Id;
        }
        
        public System.Threading.Tasks.Task<WCFClient.HTTP.StudentResponse> GetStudentAsync(WCFClient.HTTP.StudentRequest request) {
            return base.Channel.GetStudentAsync(request);
        }
    }
}
